In [61]:
TEST_X = "f24-38615-hw3/test_X.csv"
TRAIN_X = "f24-38615-hw3/train_X.csv"
TRAIN_Y = "f24-38615-hw3/train_y.csv"

In [62]:
import pandas as pd

In [63]:
x = pd.read_csv(TRAIN_X).drop(columns=['Unnamed: 0'])
# x = pd.read_csv(TRAIN_X)
# x.describe()

In [64]:
y = pd.read_csv(TRAIN_Y).drop(columns=['Unnamed: 0'])
# y = pd.read_csv(TRAIN_Y)
y

     xml_neoplasm_histologic_grade
0                                0
1                                1
2                                0
3                                0
4                                1
..                             ...
439                              1
440                              1
441                              1
442                              0
443                              1

[444 rows x 1 columns]

In [65]:
# tto_y = pd.read_csv(TRAIN_Y)
tt_x_or = pd.read_csv(TEST_X)
tt_x = tt_x_or.drop(columns=['Unnamed: 0'])
tt_x

,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,ENSG00000001460,...,ENSG00000282651,ENSG00000282815,ENSG00000282939,ENSG00000283063,ENSG00000283439,ENSG00000283463,ENSG00000283526,ENSG00000283586,ENSG00000283632,ENSG00000283697
0,7.503849,1.685440,8.090089,5.546588,3.412025,5.871539,8.395029,5.894996,6.313896,4.286261,...,3.626396,-2.640463,-7.278265,0.721287,-7.278265,4.672536,5.153675,-7.278265,4.843800,4.302864
1,6.112919,-5.425877,5.604743,4.248246,3.374033,3.370075,6.804015,4.646287,6.236134,4.167541,...,-5.425877,-2.143410,1.956699,1.377768,-5.425877,4.560829,3.735085,-5.425877,4.105789,4.803357
2,6.183846,1.217355,6.093903,4.403216,5.722867,6.123209,7.680258,4.983386,5.626569,3.518791,...,11.317818,-5.259782,5.093316,3.800607,-5.259782,4.966710,2.829487,-5.259782,5.118704,5.024979
3,6.325535,-0.197432,6.722632,4.509093,4.941256,3.700171,7.492606,5.031053,5.859242,4.252114,...,3.536141,-1.362703,3.480703,0.776383,-0.999629,4.794226,-5.399485,-5.399485,4.660878,4.684343
4,7.162383,-5.539710,6.186110,5.270282,5.412103,3.781568,7.285779,4.847552,6.337205,5.622222,...,5.112772,-5.539710,4.369268,2.927849,0.791397,4.542333,4.628775,-5.539710,4.812787,4.524834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,6.949029,2.192625,7.613706,5.131517,4.292879,5.337764,7.668408,5.159289,5.645662,3.082916,...,5.515318,-5.785898,4.229114,2.875184,-0.303496,3.322246,3.683199,-5.785898,4.730559,3.251810
106,7.419322,0.472349,6.723539,5.176782,4.297442,4.591905,7.171547,6.693665,5.782247,5.965700,...,2.737453,-1.781791,3.509502,0.021815,-6.758708,4.684549,4.795272,-6.758708,4.234056,4.614238
107,7.135800,0.479097,7.051451,6.042828,4.523706,7.250545,7.577726,5.622388,6.447874,4.835028,...,5.951147,-5.960456,4.025253,2.785925,-5.960456,4.236003,5.597498,-5.960456,5.279498,3.813894
108,6.859635,2.159767,7.254992,4.900402,4.256251,6.503227,6.810730,6.036136,6.282137,4.745579,...,4.462337,-5.553034,4.325258,2.593648,-5.553034,4.727639,2.380364,-5.553034,5.523681,4.088765
109,6.532266,0.991316,6.206966,4.272550,4.643635,3.523035,6.075602,3.796164,5.396661,3.984618,...,4.710150,-5.527237,4.706596,-5.527237,1.083984,3.687288,2.846958,-5.527237,3.600439,3.306464

In [66]:
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.metrics import accuracy_score

In [67]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [68]:
# Lasso (L1 regularization)
logreg_l1 = LogisticRegression(max_iter=10000)
logreg_l1.fit(x_train, y_train)
y_pred_l1 = logreg_l1.predict(x_test)
print("L1 Logistic Regression Accuracy: ", accuracy_score(y_test, y_pred_l1))

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

L1 Logistic Regression Accuracy:  0.8539325842696629

In [69]:

logreg_l1 = LogisticRegression(penalty='l2', solver='newton-cg', max_iter=10000)
logreg_l1.fit(x_train, y_train)
y_pred_l1 = logreg_l1.predict(x_test)
print("L1 Logistic Regression Accuracy: ", accuracy_score(y_test, y_pred_l1))

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

L1 Logistic Regression Accuracy:  0.8426966292134831

In [13]:
# Lasso (L1 regularization)
logreg_l1 = LogisticRegression(penalty='l2', solver='saga', max_iter=10000)
logreg_l1.fit(x_train, y_train)
y_pred_l1 = logreg_l1.predict(x_test)
print("L1 Logistic Regression Accuracy: ", accuracy_score(y_test, y_pred_l1))

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

L1 Logistic Regression Accuracy:  0.8426966292134831

In [ ]:
new_test_x = tt_x

In [20]:
kaggle_submit_pred = logreg_l1.predict(tt_x)
kaggle_submit_pred

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1])

In [28]:
preds = pd.DataFrame(kaggle_submit_pred)
kagpal = pd.concat([tt_x_or['Unnamed: 0'], preds], axis=1)
kagpal.to_csv('oopp.csv')

In [30]:
from sklearn.model_selection import GridSearchCV

# Hyperparameter tuning with GridSearchCV
param_grid = {'C': [0.01, 0.1, 1, 10, 100]}  # Range of regularization strengths
grid_search = GridSearchCV(LogisticRegression(penalty='l1', solver='liblinear', max_iter=10000), 
                           param_grid, cv=5)
grid_search.fit(x_train, y_train)

# Best model
best_logreg_l1 = grid_search.best_estimator_
y_pred_l1_best = best_logreg_l1.predict(x_test)
print("Best L1 Logistic Regression Accuracy: ", accuracy_score(y_test, y_pred_l1_best))
print("Best C Value: ", grid_search.best_params_)

/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Best L1 Logistic Regression Accuracy:  0.797752808988764
Best C Value:  {'C': 10}

In [69]:
from sklearn.feature_selection import SelectKBest, f_classif

# Selecting top 1000 features based on ANOVA F-test
selector = SelectKBest(f_classif, k=15000)  # Experiment with different k values
x_train_selected = selector.fit_transform(x_train, y_train)
x_test_selected = selector.transform(x_test)

logreg_l1 = LogisticRegression(penalty='l1', solver='liblinear', max_iter=10000)
logreg_l1.fit(x_train_selected, y_train)
y_pred_l1_selected = logreg_l1.predict(x_test_selected)
print("L1 Logistic Regression Accuracy after Feature Selection: ", accuracy_score(y_test, y_pred_l1_selected))

/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

L1 Logistic Regression Accuracy after Feature Selection:  0.8089887640449438

In [ ]:
# Ridge (L2) Logistic Regression
logreg_l2 = LogisticRegression(penalty='l2', max_iter=10000)
logreg_l2.fit(x_train, y_train)
y_pred_l2 = logreg_l2.predict(x_test)
print("L2 Logistic Regression Accuracy: ", accuracy_score(y_test, y_pred_l2))

L2 Logistic Regression Accuracy:  0.8539325842696629

/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

# Generate polynomial features (degree=2)
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

logreg_poly = LogisticRegression(max_iter=10000)
logreg_poly.fit(x_train_poly, y_train)
y_pred_poly = logreg_poly.predict(x_test_poly)
print("Logistic Regression Accuracy with Polynomial Features: ", accuracy_score(y_test, y_pred_poly))

In [74]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

logreg_l1 = LogisticRegression(penalty='l1', solver='liblinear', max_iter=10000)
logreg_l1.fit(x_train_scaled, y_train)
y_pred_l1_scaled = logreg_l1.predict(x_test_scaled)
print("L1 Logistic Regression Accuracy with Scaling: ", accuracy_score(y_test, y_pred_l1_scaled))

/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

L1 Logistic Regression Accuracy with Scaling:  0.797752808988764

In [75]:
from sklearn.model_selection import cross_val_score

import numpy as np

logreg_l1 = LogisticRegression(penalty='l1', solver='liblinear', max_iter=10000)
cv_scores = cross_val_score(logreg_l1, x_train, y_train, cv=5)
print("Cross-Validation Scores: ", cv_scores)
print("Mean CV Accuracy: ", np.mean(cv_scores))

/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/pdf/lib/python3.9/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Cross-Validation Scores:  [0.81690141 0.74647887 0.84507042 0.74647887 0.84507042]
Mean CV Accuracy:  0.8

In [98]:
from sklearn.ensemble import GradientBoostingClassifier
# from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score


# Initialize the Gradient Boosting Classifier

gb_model = GradientBoostingClassifier(loss='log_loss', n_estimators=1200, learning_rate=1, max_depth=7, random_state=42)
# tuning = RandomizedSearchCV(estimator=GradientBoostingClassifier(), param_distributions = gb_model scoring="r2")
# tuning.fit(x_train, y_train)
# Train the model on the training set
gb_model.fit(x_train, y_train)

# Make predictions on the test set
y_pred_gb = gb_model.predict(x_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred_gb)
print("Gradient Boosting Classifier Accuracy: ", accuracy)

# Optional: Print detailed classification report
print("Gradient Boosting Classification Report:\n", classification_report(y_test, y_pred_gb))

# Optional: Compute ROC-AUC score for more insight
y_pred_gb_prob = gb_model.predict_proba(x_test)[:, 1]  # Use probabilities for ROC-AUC
roc_auc = roc_auc_score(y_test, y_pred_gb_prob)
print("Gradient Boosting ROC-AUC Score: ", roc_auc)

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Gradient Boosting Classifier Accuracy:  0.7640449438202247
Gradient Boosting Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.75      0.72        36
           1       0.82      0.77      0.80        53

    accuracy                           0.76        89
   macro avg       0.76      0.76      0.76        89
weighted avg       0.77      0.76      0.77        89

Gradient Boosting ROC-AUC Score:  0.8443396226415094

### Check Here

In [136]:
#using mutual_info_classif for classification problem MI
from sklearn.feature_selection import mutual_info_classif

mi_scores = mutual_info_classif(x, y)
mi_scores = pd.Series(mi_scores, name="MI Scores", index=x.columns)
mi_scores = mi_scores.sort_values(ascending=False)

mi_scores # show a few features with their MI scores

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ENSG00000101448    0.155757
ENSG00000101443    0.155406
ENSG00000163071    0.150078
ENSG00000243543    0.149875
ENSG00000103056    0.145172
                     ...
ENSG00000166130    0.000000
ENSG00000166128    0.000000
ENSG00000102974    0.000000
ENSG00000102978    0.000000
ENSG00000167037    0.000000
Name: MI Scores, Length: 17970, dtype: float64

In [141]:
use = []
for feat in mi_scores:
    if feat > 0:
        use.append(x.columns)
print(len(use))

13053

In [ ]:
x = df[use]

In [134]:
from sklearn.feature_selection import SelectKBest, mutual_info_regression
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.feature_selection import SelectKBest, chi2, mutual_info_classif

k = 13053  # Specify the number of features you want best is 16000
selector = SelectKBest(chi2, k=k)
X_train_selected = selector.fit_transform(x_train, y_train)
X_test_selected = selector.transform(x_test)
x_new_test = selector.transform(tt_x)

log_reg = LogisticRegression(max_iter=50000, random_state=42)  # max_iter increased for convergence
log_reg.fit(X_train_selected, y_train)

# Step 4: Make predictions and evaluate
y_pred = log_reg.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy with Logistic Regression: {accuracy:.4f}")

ValueError: Input X must be non-negative.

In [133]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.metrics import accuracy_score
# Initialize base models

k = 16000  # Specify the number of features you want best is 16000
selector = SelectKBest(score_func=f_classif, k=k)
X_train_selected = selector.fit_transform(x_train, y_train)
X_test_selected = selector.transform(x_test)
x_new_test = selector.transform(tt_x)

log_reg = LogisticRegression(max_iter=50000, random_state=42)  # max_iter increased for convergence
gbc = GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_depth=3, random_state=42)
stacking_clf = StackingClassifier(estimators=[('gb', gbc)], final_estimator=log_reg)
stacking_clf.fit(X_train_selected, y_train)

# Step 4: Make predictions and evaluate
y_pred = stacking_clf.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy with Logistic Regression: {accuracy:.4f}")

# logreg = LogisticRegression(max_iter=10000)
# gbc = GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_depth=3, random_state=42)

# # Define the stacking classifier with logistic regression as the final model
# stacking_clf = StackingClassifier(estimators=[('gb', gbc)], final_estimator=logreg)

# # Train the stacking model
# stacking_clf.fit(x_train, y_train)

# Make predictions
# y_pred_stack = stacking_clf.predict(x_test)

# # Evaluate the accuracy
# accuracy = accuracy_score(y_test, y_pred_stack)
# print("Stacking Model Accuracy: ", accuracy)

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

Accuracy with Logistic Regression: 0.8090

In [142]:
from sklearn.feature_selection import SelectKBest, f_classif

k = 13053  # Specify the number of features you want best is 16000
selector = SelectKBest(score_func=f_classif, k=k)
X_train_selected = selector.fit_transform(x_train, y_train)
X_test_selected = selector.transform(x_test)
x_new_test = selector.transform(tt_x)

log_reg = LogisticRegression(max_iter=50000, random_state=42)  # max_iter increased for convergence
log_reg.fit(X_train_selected, y_train)

# Step 4: Make predictions and evaluate
y_pred = log_reg.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy with Logistic Regression: {accuracy:.4f}")

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy with Logistic Regression: 0.8652

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [117]:
from sklearn.feature_selection import SelectKBest, f_classif

k = 16000  # Specify the number of features you want
selector = SelectKBest(score_func=f_classif, k=k)
X_train_selected = selector.fit_transform(x_train, y_train)
X_test_selected = selector.transform(x_test)
x_new_test = selector.transform(tt_x)

gb_model = GradientBoostingClassifier(n_estimators=250, learning_rate=0.1, max_depth=5, random_state=42)

# Train the model on the training set
gb_model.fit(X_train_selected, y_train)

# Step 4: Make predictions and evaluate
y_pred = gb_model.predict(X_test_selected)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy with: {accuracy:.4f}")

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy with: 0.6966

In [95]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier


# Step 2: Apply PCA (optional, depending on the dimensionality reduction needed)
# Retain 95% of variance or choose a fixed number of components
pca = PCA(n_components=0.98, random_state=42)  # Adjust n_components based on your preference

# Fit PCA on the training data and transform both training and test data
X_train_pca = pca.fit_transform(x_train)
X_test_pca = pca.transform(x_test)
x_new_test_pca = pca.transform(tt_x)

# Step 3: Initialize the Gradient Boosting Classifier

gb_model = GradientBoostingClassifier(loss='log_loss', n_estimators=1200, learning_rate=1, max_depth=7, random_state=42)

# Train the model on the training set
gb_model.fit(X_train_pca, y_train)

# log_reg = LogisticRegression(max_iter=5000, random_state=42)  # max_iter increased for convergence
# log_reg.fit(X_train_pca, y_train)

# Step 4: Make predictions and evaluate
y_pred = gb_model.predict(X_test_pca)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy with Logistic Regression: {accuracy:.4f}")

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy with Logistic Regression: 0.8202

In [72]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier(n_estimators=250, learning_rate=0.1, max_depth=7, random_state=42)
xgb_model.fit(x_train, y_train)
y_pred = xgb_model.predict(x_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

XGBoostError:
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <B9202094-7D52-318C-99CF-7034B0E9F28D> /opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/lib-dynload/../../libomp.dylib' (no such file), '/opt/homebrew/anaconda3/envs/CMU_ML/bin/../lib/libomp.dylib' (no such file)"]

In [43]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Step 1: Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)  # Assuming X is your feature matrix

# Step 2: Apply PCA
# We retain enough components to explain 95% of the variance
pca = PCA(n_components=0.90)  # Retain 95% variance
X_pca = pca.fit_transform(X_scaled)

# Step 3: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# Step 4: Train Gradient Boosting Classifier on the PCA-reduced data
gb_model = GradientBoostingClassifier(n_estimators=250, learning_rate=0.1, max_depth=7, random_state=42)
gb_model.fit(X_train, y_train)

# Step 5: Make predictions and evaluate
y_pred = gb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy after PCA: {accuracy:.4f}")

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy after PCA: 0.6854

In [32]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Initialize base models
logreg = LogisticRegression(max_iter=10000)
gbc = GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_depth=3, random_state=42)

# Define the stacking classifier with logistic regression as the final model
stacking_clf = StackingClassifier(estimators=[('gb', gbc)], final_estimator=logreg)

# Train the stacking model
stacking_clf.fit(x_train, y_train)

# Make predictions
y_pred_stack = stacking_clf.predict(x_test)

# Evaluate the accuracy
accuracy = accuracy_score(y_test, y_pred_stack)
print("Stacking Model Accuracy: ", accuracy)

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

Stacking Model Accuracy:  0.8202247191011236

In [58]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Step 1: Standardize the features
# scaler = StandardScaler()
# X_scaled = scaler.fit_transform(x)  # Assuming X is your feature matrix

# Step 2: Apply PCA
# We retain enough components to explain 95% of the variance
pca = PCA(n_components=0.75, random_state=42)  # Retain 95% variance
x_pca = pca.fit_transform(x)

# Step 3: Train-Test Split
x_train, X_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.2, random_state=42)

# Step 4: Train Gradient Boosting Classifier on the PCA-reduced data
gb_model = GradientBoostingClassifier(n_estimators=1550, learning_rate=0.1, max_depth=6, random_state=42)
gb_model.fit(x_train, y_train)

# Step 5: Make predictions and evaluate
y_pred = gb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy after PCA: {accuracy:.4f}")

/opt/homebrew/anaconda3/envs/CMU_ML/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy after PCA: 0.8202

In [143]:

y_pred_gb = log_reg.predict(x_new_test)
y_pred_gb

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1])

In [97]:
y_pred_gb = gb_model.predict(x_new_test_pca)
y_pred_gb

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0])

In [144]:
preds = pd.DataFrame(y_pred_gb)
rampal = pd.concat([tt_x_or['Unnamed: 0'], preds], axis=1)
rampal.to_csv('output7.csv', index=False)